// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameApi.Data;

#nullable disable

namespace VideoGameApi.Migrations
{
    [DbContext(typeof(VideoGameDbContext))]
    partial class VideoGameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoGameApi.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plataform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "Nintendo EPD",
                            Plataform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "Santa Monica Studio",
                            Plataform = "PlayStation 5",
                            Publisher = "Sony Interactive Entertainment",
                            Title = "God of War: Ragnarök"
                        },
                        new
                        {
                            Id = 3,
                            Developer = "FromSoftware",
                            Plataform = "PC",
                            Publisher = "Bandai Namco Entertainment",
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 4,
                            Developer = "Rockstar Games",
                            Plataform = "Xbox One",
                            Publisher = "Rockstar Games",
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 5,
                            Developer = "Nintendo EPD",
                            Plataform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Title = "Super Mario Odyssey"
                        },
                        new
                        {
                            Id = 6,
                            Developer = "343 Industries",
                            Plataform = "Xbox Series X/S",
                            Publisher = "Xbox Game Studios",
                            Title = "Halo Infinite"
                        },
                        new
                        {
                            Id = 7,
                            Developer = "Insomniac Games",
                            Plataform = "PlayStation 5",
                            Publisher = "Sony Interactive Entertainment",
                            Title = "Spider-Man 2"
                        },
                        new
                        {
                            Id = 8,
                            Developer = "CD Projekt Red",
                            Plataform = "PC",
                            Publisher = "CD Projekt",
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 9,
                            Developer = "Mojang Studios",
                            Plataform = "Multi-platform",
                            Publisher = "Microsoft Studios",
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 10,
                            Developer = "Epic Games",
                            Plataform = "Multi-platform",
                            Publisher = "Epic Games",
                            Title = "Fortnite"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
